# Generated by Django 3.2.5 on 2022-05-11 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('vote_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_date', models.DateTimeField(verbose_name='Conference Start')),
                ('abstract', models.CharField(default='The organizers were lazy and left nothing.', max_length=1000)),
                ('programme_judge_num', models.IntegerField(default=2)),
                ('head_judge_num', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=100)),
                ('file_width', models.IntegerField(default=0)),
                ('file_height', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='000000', max_length=10)),
                ('position', models.CharField(default='No position', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.staff')),
            ],
            bases=('polls.staff',),
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.staff')),
            ],
            bases=('polls.staff',),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.staff')),
            ],
            bases=('polls.staff',),
        ),
        migrations.CreateModel(
            name='HeadJudge',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.staff')),
                ('score_status', models.IntegerField(default=0)),
            ],
            bases=('polls.staff',),
        ),
        migrations.CreateModel(
            name='ProgrammeJudge',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.staff')),
                ('score_status', models.IntegerField(default=0)),
            ],
            bases=('polls.staff',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
