# Generated by Django 3.2.5 on 2022-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headjudge',
            name='division',
            field=models.CharField(default='dst', max_length=10),
        ),
        migrations.AddField(
            model_name='programmejudge',
            name='prgramme',
            field=models.CharField(default='cst', max_length=10),
        ),
    ]
