# Generated by Django 3.2.5 on 2022-05-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220512_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmejudge',
            old_name='prgramme',
            new_name='programme',
        ),
    ]
