# Generated by Django 3.2.5 on 2022-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_prgramme_programmejudge_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='count_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poster',
            name='number_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poster',
            name='total_rate',
            field=models.IntegerField(default=0),
        ),
    ]
