# Generated by Django 3.2.5 on 2022-05-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220513_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('code', models.IntegerField(max_length=6)),
                ('send_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
